FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI=true
RUN corepack enable


FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter order-service build

RUN pnpm --filter order-service --prod deploy --legacy /app/deployed


FROM node:20-alpine AS runner
WORKDIR /app

COPY --from=builder /app/deployed ./
COPY --from=builder /app/services/order-service/dist ./dist

EXPOSE 3004

CMD ["node", "dist/server.js"]